version: "3"

services:
  dev:
    build: .
    env_file: .env
    volumes:
      - ./input:/work/input
      - ./output:/work/output
      - ${SOURCE_CODE:-./source_code}:/work/source_code
    command: npx tailwindcss-cli@latest build /work/input/tailwind.css -o /work/output/tailwind.css

  prod:
    build: .
    env_file: .env
    volumes:
      - ./input:/work/input
      - ./output:/work/output
      - ${SOURCE_CODE:-./source_code}:/work/source_code
    environment:
      - NODE_ENV=production
    command: /bin/sh prod.sh

volumes:
  input:
  output:
  source_code: